In [1]:
from sklearn.datasets import load_iris

import pandas as pd
import numpy as np

np.random.seed(0)

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)

#Just adding the Y column, classification column
df['Species Class'] = pd.DataFrame(iris.target)

df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species Class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [3]:
X = df
X = X.drop(['Species Class'], axis = 1)

Y = pd.DataFrame()
Y['Species Class'] = df['Species Class']

print(X)
print(Y)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
     Species Class
0                0
1                0
2                0
3                0
4                0
..             ...
145              2
146              2
147              2
148              2
149              2

[150 rows x 1 columns]

In [4]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(X, Y, train_size = 0.7, stratify = Y, 
                                                 shuffle = None, random_state = np.random.randint(low = 1, high = 50))

# (shuffle = True/False) will shuffle or nor the train and test data
# (stratify = y/None) will make sure sure the test & train set it proportionate and not
# --------Cannot set shuffle and stratify both at a time---------------------

#random_state deals with the randomness of the split operation
#It's customary to add both train_size & test_size. It will automatically calculate from any one of
#                         the train_size and test size(Which will be given)
#stratify = y --> will make sure the test and train data is well proportionate
#to shuffle and disregard the proportion, shuffle = True can be set in the place of stratify

In [5]:
print("Number of training examples: ", len(train_x))
print("Number of testing examples: ", len(test_x))

Number of training examples:  105
Number of testing examples:  45

In [6]:
train_x.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
108                6.7               2.5                5.8               1.8
6                  4.6               3.4                1.4               0.3
37                 4.9               3.6                1.4               0.1
67                 5.8               2.7                4.1               1.0
117                7.7               3.8                6.7               2.2

In [7]:
train_y.head()

     Species Class
108              2
6                0
37               0
67               1
117              2

In [8]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_jobs = 4, random_state = 0)
clf.fit(train_x, train_y.values.ravel())

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=4,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [9]:
test_x.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
56                 6.3               3.3                4.7               1.6
11                 4.8               3.4                1.6               0.2
140                6.7               3.1                5.6               2.4
23                 5.1               3.3                1.7               0.5
35                 5.0               3.2                1.2               0.2

In [10]:
test_data = test_x
test_data.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
56                 6.3               3.3                4.7               1.6
11                 4.8               3.4                1.6               0.2
140                6.7               3.1                5.6               2.4
23                 5.1               3.3                1.7               0.5
35                 5.0               3.2                1.2               0.2

In [11]:
def name(sl):
    if (sl == '0'): return 'setosa'
    elif(sl == '1'): return 'versicolor'
    else: return 'virginica'

In [12]:
prediction = clf.predict(test_x)
P = pd.DataFrame({'Prediction': prediction[:]}, index = test_data.index)
P.head()

test_data = test_data.join(test_y)
test_data = test_data.join(P)

test_data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species Class,Prediction
56,6.3,3.3,4.7,1.6,1,1
11,4.8,3.4,1.6,0.2,0,0
140,6.7,3.1,5.6,2.4,2,2
23,5.1,3.3,1.7,0.5,0,0
35,5.0,3.2,1.2,0.2,0,0
147,6.5,3.0,5.2,2.0,2,2
21,5.1,3.7,1.5,0.4,0,0
121,5.6,2.8,4.9,2.0,2,2
88,5.6,3.0,4.1,1.3,1,1
14,5.8,4.0,1.2,0.2,0,0
77,6.7,3.0,5.0,1.7,1,2
90,5.5,2.6,4.4,1.2,1,1
91,6.1,3.0,4.6,1.4,1,1
15,5.7,4.4,1.5,0.4,0,0
133,6.3,2.8,5.1,1.5,2,1
142,5.8,2.7,5.1,1.9,2,2
89,5.5,2.5,4.0,1.3,1,1
12,4.8,3.0,1.4,0.1,0,0
61,5.9,3.0,4.2,1.5,1,1
107,7.3,2.9,6.3,1.8,2,2
106,4.9,2.5,4.5,1.7,2,1
1,4.9,3.0,1.4,0.2,0,0
30,4.8,3.1,1.6,0.2,0,0
8,4.4,2.9,1.4,0.2,0,0
32,5.2,4.1,1.5,0.1,0,0
78,6.0,2.9,4.5,1.5,1,1
97,6.2,2.9,4.3,1.3,1,1
101,5.8,2.7,5.1,1.9,2,2
66,5.6,3.0,4.5,1.5,1,1
38,4.4,3.0,1.3,0.2,0,0
93,5.0,2.3,3.3,1.0,1,1
4,5.0,3.6,1.4,0.2,0,0
145,6.7,3.0,5.2,2.3,2,2
31,5.4,3.4,1.5,0.4,0,0
82,5.8,2.7,3.9,1.2,1,1
55,5.7,2.8,4.5,1.3,1,1
137,6.4,3.1,5.5,1.8,2,2
119,6.0,2.2,5.0,1.5,2,1
127,6.1,3.0,4.9,1.8,2,2
3,4.6,3.1,1.5,0.2,0,0
96,5.7,2.9,4.2,1.3,1,1
141,6.9,3.1,5.1,2.3,2,2
74,6.4,2.9,4.3,1.3,1,1
149,5.9,3.0,5.1,1.8,2,2
114,5.8,2.8,5.1,2.4,2,2

In [13]:
#Naming the classes

test_data['Species Class'] = test_data['Species Class'].astype(str)
test_data['Prediction'] = test_data['Prediction'].astype(str)

for i in range(len(test_data)):
    pos = test_data.index[i]
    test_data.loc[pos, 'Species Class'] = name(test_data['Species Class'][pos])
    test_data.loc[pos, 'Prediction'] = name(test_data['Prediction'][pos])

test_data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species Class,Prediction
56,6.3,3.3,4.7,1.6,versicolor,versicolor
11,4.8,3.4,1.6,0.2,setosa,setosa
140,6.7,3.1,5.6,2.4,virginica,virginica
23,5.1,3.3,1.7,0.5,setosa,setosa
35,5.0,3.2,1.2,0.2,setosa,setosa
147,6.5,3.0,5.2,2.0,virginica,virginica
21,5.1,3.7,1.5,0.4,setosa,setosa
121,5.6,2.8,4.9,2.0,virginica,virginica
88,5.6,3.0,4.1,1.3,versicolor,versicolor
14,5.8,4.0,1.2,0.2,setosa,setosa
77,6.7,3.0,5.0,1.7,versicolor,virginica
90,5.5,2.6,4.4,1.2,versicolor,versicolor
91,6.1,3.0,4.6,1.4,versicolor,versicolor
15,5.7,4.4,1.5,0.4,setosa,setosa
133,6.3,2.8,5.1,1.5,virginica,versicolor
142,5.8,2.7,5.1,1.9,virginica,virginica
89,5.5,2.5,4.0,1.3,versicolor,versicolor
12,4.8,3.0,1.4,0.1,setosa,setosa
61,5.9,3.0,4.2,1.5,versicolor,versicolor
107,7.3,2.9,6.3,1.8,virginica,virginica
106,4.9,2.5,4.5,1.7,virginica,versicolor
1,4.9,3.0,1.4,0.2,setosa,setosa
30,4.8,3.1,1.6,0.2,setosa,setosa
8,4.4,2.9,1.4,0.2,setosa,setosa
32,5.2,4.1,1.5,0.1,setosa,setosa
78,6.0,2.9,4.5,1.5,versicolor,versicolor
97,6.2,2.9,4.3,1.3,versicolor,versicolor
101,5.8,2.7,5.1,1.9,virginica,virginica
66,5.6,3.0,4.5,1.5,versicolor,versicolor
38,4.4,3.0,1.3,0.2,setosa,setosa
93,5.0,2.3,3.3,1.0,versicolor,versicolor
4,5.0,3.6,1.4,0.2,setosa,setosa
145,6.7,3.0,5.2,2.3,virginica,virginica
31,5.4,3.4,1.5,0.4,setosa,setosa
82,5.8,2.7,3.9,1.2,versicolor,versicolor
55,5.7,2.8,4.5,1.3,versicolor,versicolor
137,6.4,3.1,5.5,1.8,virginica,virginica
119,6.0,2.2,5.0,1.5,virginica,versicolor
127,6.1,3.0,4.9,1.8,virginica,virginica
3,4.6,3.1,1.5,0.2,setosa,setosa
96,5.7,2.9,4.2,1.3,versicolor,versicolor
141,6.9,3.1,5.1,2.3,virginica,virginica
74,6.4,2.9,4.3,1.3,versicolor,versicolor
149,5.9,3.0,5.1,1.8,virginica,virginica
114,5.8,2.8,5.1,2.4,virginica,virginica

In [14]:
y_test = test_data['Species Class']
predicted = test_data['Prediction']

In [15]:
CM = pd.crosstab(y_test, predicted)

In [16]:
from sklearn.metrics import multilabel_confusion_matrix

CM_multiclass = multilabel_confusion_matrix(test_data['Species Class'], test_data['Prediction'], 
                            labels = ["setosa", "versicolor", "virginica"])

In [17]:
from sklearn.metrics import precision_recall_fscore_support as score
precision, recall, fscore, support = score(y_test, predicted)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

precision: [1.         0.82352941 0.92307692]
recall: [1.         0.93333333 0.8       ]
fscore: [1.         0.875      0.85714286]
support: [15 15 15]